### ISSUE TITLE
内存溢出🤔

### ISSUE THREAD

**Issue by hezhijie0327** [hezhijie0327/DHDb#2]
Processing...
./extractor.sh: xrealloc: cannot allocate 18446744071646993920 bytes (65536 bytes allocated)
"/root/example/querylog-Atroc-1616921354.txt" has been generated.

_Originally posted by @Atroc-0625 in https://github.com/hezhijie0327/DHDb/issues/1#issuecomment-808867138_

**Comment by ghost** [comment]
感觉是文件太大的原因导致的？

**Comment by hezhijie0327** [comment]
1. 有可能，稍后我再看看，能不能把这解决掉
2. 目前查到的相关资料来讲都指向 [`bash`](https://lists.gnu.org/archive/html/bug-bash/2015-06/msg00083.html) 的问题

**Comment by hezhijie0327** [comment]
试试问题是否解决

**Comment by ghost** [comment]
> 试试问题是否解决

谢谢，已经解决，稍后邮件发送给你
